name: CI
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: CC=gcc-14 CFLAGS=-Werror make
      - run: clang-format --dry-run --Werror src/*
      - run: clang-tidy -p build/cmake --warnings-as-errors='*' src/*.c
